@startuml
start
:Log in;
:Check reservations;
if (Are tables free?) then (yes)
    :Reserve a table;
    :Browse through menu;
    :Plaace an order;
    :Eat meal;
    repeat :Proceed to payment;
    ' split :Offline;
    ' split again repeat:Online;
    backward :Retry payment;
    repeat while (Payment successfull?) is (no) not (yes)
   :Take receipt;
else (no)
    :Book for future;
endif
:Log out;
stop
@enduml